//HintName: TestNamespace.OrderId.g.cs
// <auto-generated />
#nullable enable

using System;
using System.ComponentModel;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TestNamespace;

[JsonConverter(typeof(OrderIdJsonConverter))]
[TypeConverter(typeof(OrderIdTypeConverter))]
public readonly partial struct OrderId 
    : IEquatable<OrderId>, IComparable<OrderId>, IParsable<OrderId>
{
    public string Value => _value ?? string.Empty;
    private string _value;

    public OrderId(string value) => _value = value;

    public static OrderId From(string value) => !string.IsNullOrEmpty(value)
      ? new(value)
      : throw new ArgumentException("Value cannot be empty", nameof(value));
    public static OrderId Empty => new("");

    // Equality
    public bool Equals(OrderId other) => Value.Equals(other.Value);
    public override bool Equals(object? obj) => obj is OrderId other && Equals(other);
    public override int GetHashCode() => Value.GetHashCode();
    public static bool operator ==(OrderId left, OrderId right) => left.Equals(right);
    public static bool operator !=(OrderId left, OrderId right) => !left.Equals(right);

    // Comparable
    public int CompareTo(OrderId other) => Value.CompareTo(other.Value);

    // Parse
    public static OrderId Parse(string s, IFormatProvider? provider = null) 
        => From(s);
    public static bool TryParse(string? s, IFormatProvider? provider, out OrderId result)
    {
        if (!string.IsNullOrEmpty(s)) 
        {
              result = new(s);
              return true;
        }
        result = default;
        return false;
    }

    public override string ToString() => Value;

    // Implicit/explicit conversions
    public static explicit operator OrderId(string value) => new(value);
    public static implicit operator string(OrderId id) => id.Value;

    // JSON converter
    public sealed class OrderIdJsonConverter : JsonConverter<OrderId>
    {
        public override OrderId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            => new(reader.GetString());
        public override void Write(Utf8JsonWriter writer, OrderId value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.Value);
    }

    // TypeConverter (for model binding, route parameters, etc.)
    public sealed class OrderIdTypeConverter : TypeConverter
    {
        public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType) 
            => sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
        public override object? ConvertFrom(ITypeDescriptorContext? context, System.Globalization.CultureInfo? culture, object value) 
            => value switch
            {
                string s => Parse(s),
                _ => base.ConvertFrom(context, culture, value)
            };
    }
}